services:
  aipi-bench:
    build: .
    container_name: aipi-bench
    restart: always
    ports:
      - 1808:3000
    env_file:
      - .env
    volumes:
      - /home/user/projects/aipi-bench/data:/app/data
      - /home/user/projects/aipi-bench/config.json:/app/config.json:ro
